/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ProfessionRouteImport } from './routes/profession'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GeneratingRouteImport } from './routes/generating'
import { Route as FilmRouteImport } from './routes/film'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsBrandRouteImport } from './routes/settings.brand'
import { Route as IdeasFormatRouteImport } from './routes/ideas.$format'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionRoute = ProfessionRouteImport.update({
  id: '/profession',
  path: '/profession',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratingRoute = GeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmRoute = FilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBrandRoute = SettingsBrandRouteImport.update({
  id: '/settings/brand',
  path: '/settings/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasFormatRoute = IdeasFormatRouteImport.update({
  id: '/ideas/$format',
  path: '/ideas/$format',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/editing': typeof EditingRoute
  '/film': typeof FilmRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/profession': typeof ProfessionRoute
  '/templates': typeof TemplatesRoute
  '/ideas/$format': typeof IdeasFormatRoute
  '/settings/brand': typeof SettingsBrandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/editing': typeof EditingRoute
  '/film': typeof FilmRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/profession': typeof ProfessionRoute
  '/templates': typeof TemplatesRoute
  '/ideas/$format': typeof IdeasFormatRoute
  '/settings/brand': typeof SettingsBrandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/editing': typeof EditingRoute
  '/film': typeof FilmRoute
  '/generating': typeof GeneratingRoute
  '/onboarding': typeof OnboardingRoute
  '/profession': typeof ProfessionRoute
  '/templates': typeof TemplatesRoute
  '/ideas/$format': typeof IdeasFormatRoute
  '/settings/brand': typeof SettingsBrandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit'
    | '/editing'
    | '/film'
    | '/generating'
    | '/onboarding'
    | '/profession'
    | '/templates'
    | '/ideas/$format'
    | '/settings/brand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit'
    | '/editing'
    | '/film'
    | '/generating'
    | '/onboarding'
    | '/profession'
    | '/templates'
    | '/ideas/$format'
    | '/settings/brand'
  id:
    | '__root__'
    | '/'
    | '/edit'
    | '/editing'
    | '/film'
    | '/generating'
    | '/onboarding'
    | '/profession'
    | '/templates'
    | '/ideas/$format'
    | '/settings/brand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  EditingRoute: typeof EditingRoute
  FilmRoute: typeof FilmRoute
  GeneratingRoute: typeof GeneratingRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfessionRoute: typeof ProfessionRoute
  TemplatesRoute: typeof TemplatesRoute
  IdeasFormatRoute: typeof IdeasFormatRoute
  SettingsBrandRoute: typeof SettingsBrandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profession': {
      id: '/profession'
      path: '/profession'
      fullPath: '/profession'
      preLoaderRoute: typeof ProfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generating': {
      id: '/generating'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film': {
      id: '/film'
      path: '/film'
      fullPath: '/film'
      preLoaderRoute: typeof FilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/brand': {
      id: '/settings/brand'
      path: '/settings/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof SettingsBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$format': {
      id: '/ideas/$format'
      path: '/ideas/$format'
      fullPath: '/ideas/$format'
      preLoaderRoute: typeof IdeasFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  EditingRoute: EditingRoute,
  FilmRoute: FilmRoute,
  GeneratingRoute: GeneratingRoute,
  OnboardingRoute: OnboardingRoute,
  ProfessionRoute: ProfessionRoute,
  TemplatesRoute: TemplatesRoute,
  IdeasFormatRoute: IdeasFormatRoute,
  SettingsBrandRoute: SettingsBrandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
